### ISSUE TITLE
Live stream crash after update

### ISSUE THREAD

**Issue by taimurasad** [KhaosT/homebridge-nest-cam#18]
Hi

Updated Homebridge
updated Homebridge-Nest-cam

and now all of a sudden my live stream of cameras are crashing. Running the setup on RPi3. Was working fine before the update.

this is the crash:

/usr/lib/node_modules/homebridge-nest-cam/lib/streamer.js:339
      let ssrc = crypto.randomBytes(4).readUInt32BE(0, true);
                 ^

ReferenceError: crypto is not defined
    at NexusStreamer.prepareStream (/usr/lib/node_modules/homebridge-nest-cam/lib/streamer.js:339:18)
    at NestCam.prepareStream (/usr/lib/node_modules/homebridge-nest-cam/lib/nestcam.js:115:14)
    at StreamController._handleSetupWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:540:23)
    at Characteristic.SetupEndpoints.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:271:12)
    at emitMany (events.js:147:13)
    at Characteristic.SetupEndpoints.emit (events.js:224:7)
    at Characteristic.SetupEndpoints.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:319:10)
    at Accessory.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:867:22)
    at Array.forEach (<anonymous>)
    at Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:807:8)

What could be the issue?

Here are the npm version details

{ npm: '5.5.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.1',
  openssl: '1.0.2m',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.47',
  zlib: '1.2.11' }

**Comment by KhaosT** [comment]
Sorry. Please try the updated v0.0.7.

**Comment by KhaosT** [comment]
Huh this is interesting. Would you mind give v0.0.9 a try?

**Comment by taimurasad** [comment]
Updated. Seems to be working much more reliably now. Tried loading 3 different streams from 3 different cameras and all loaded live stream in under 10 seconds on first try! Thank you so much for such quick response and fix!

**Comment by KhaosT** [comment]
No problem! Feel free to re-open the issue if this happens again.
