### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ngrimes08** [KhaosT/homebridge-nest-cam#48]
Does this not work with homebridge on windows? worked on my mac, but moving homebridge over to my windows computer to free up resources. have the new token thing working, but when i go to view live feed of camera, homebride shuts down on windows. 
here is the error:
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by damianromanowski** [comment]
You need to install the windows version of FFmpeg.

**Comment by ngrimes08** [comment]
I figured that out eventually late last night, but now I don’t get a live stream, but it doesn’t crash homebridge.  Also i appreciate your help and coding of this package!

**Comment by muzzymate** [comment]
I have both the thumbnail and video stream working on a Windows 10 machine. On the instance that I have the Nest-Cam plugin, I am also installing and loading in homebridge-camera-ffmpeg plugin. However, i do not specify anything in the config.json file for homebridge-camera-ffmpeg plugin other than in my allowed plugins list (but that's more for running multiple instances of Homebridge). 

"plugins": [
           "homebridge-camera-ffmpeg",
           .....,
           "homebridge-nest-cam",
           .....
  ],


However, I also use this machine as a media server and bluray ripping machine, so I have installed other things like Plex, Handbrake, and MakeMKV which could have slipped in ffmpeg somewhere that the nest-cam plugin is pulling form.
