### ISSUE TITLE
Live stream disconnecting

### ISSUE THREAD

**Issue by damianromanowski** [KhaosT/homebridge-nest-cam#49]
Everything seems to work properly aside from live view disconnecting after about 2 minutes into the stream.

> [NexusStreamer]Connected
> [NexusStreamer]OK
> [NexusStreamer]Playback Begin
...
...
> [NexusStreamer]Connection Closed

The home app subsequently displays: `No Response` `This camera is not responding`

I'm not sure if this is normal behaviour since I do not own any other HomeKit compatible cameras. Is the stream limited to a certain number of seconds? Or is this indeed a bug?

**Comment by ngrimes08** [comment]
i get this error
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)

**Comment by gfungsynergygateway** [comment]
Same I can only get it to work under a minute, is this normal?

**Comment by dpyy** [comment]
Same I can only get it to work under a minute, is this normal?
