### ISSUE TITLE
access_token is not defined in the Homebridge config

### ISSUE THREAD

**Issue by hjtech** [KhaosT/homebridge-nest-cam#51]
Plugin stopped working, updated to the latest version and keep getting the following error: 

`/usr/local/lib/node_modules/homebridge-nest-cam/index.js:38
      throw new Error('access_token is not defined in the Homebridge config');
            ^
Error: access_token is not defined in the Homebridge config
`
The token was generated and added to the config. The config file appears to be formatted properly:

`        {
            "platform": "Nest-cam",
            "access_token": "token here",
            "useOMX": false
        },`

**Comment by KhaosT** [comment]
Sorry would you mind to try update to `v0.0.14` and see if that fix the issue for you?

**Comment by hjtech** [comment]
Thank you @KhaosT. It is working now with the latest version.

**Comment by KhaosT** [comment]
Cool :)

**Comment by NFZ12** [comment]
I am having the same issue. Trying to setup plugin but getting the follow error:  
                       
/usr/local/lib/node_modules/homebridge-nest-cam/index.js:38
      throw new Error('access_token is not defined in the Homebridge config');
      ^

Error: access_token is not defined in the Homebridge config
    at NestCamPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-nest-cam/index.js:38:13)
    at API.emit (events.js:189:13)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
