### ISSUE TITLE
Issue After Updating Nest-Cam to 0.0.17

### ISSUE THREAD

**Issue by JoshCash** [KhaosT/homebridge-nest-cam#60]
Now I receive this error when I try to launch Homebridge:

[2019-1-22 10:00:02] [Nest-cam] Initializing Nest-cam platform...
Load homebridge-camera-ffmpeg-omx.Camera-ffmpeg-omx
/usr/local/lib/node_modules/homebridge-nest-cam/index.js:38
      throw new Error('access_token is not defined in the Homebridge config');
      ^

Error: access_token is not defined in the Homebridge config
    at NestCamPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-nest-cam/index.js:38:13)
    at emitNone (events.js:111:20)
    at API.emit (events.js:208:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:99:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by ayn** [comment]
Are you still using username and password in the config? Check the [README](https://github.com/KhaosT/homebridge-nest-cam/blob/master/README.md) on how to get a token. Nest authentication was changed in [this commit](6a4c58a9814d82a6d522b3095378f736e05df759).

**Comment by JoshCash** [comment]
So I updated my son config, and ran: curl -X "POST" "https://home.nest.com/session" \
     -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
     --data-urlencode "email=YOUR_NEST_EMAIL" \
     --data-urlencode "password=YOUR_PASSWORD"

Even when I replace the YOUR_NEST_EMAIL and YOUR_PASSWORD with my email address and password, I get this back as a response: {"url":"/session","message":"400 Bad Request"}Joshs-iMac:

**Comment by ngrimes08** [comment]
i get this error message now after updating 

[NexusStreamer]Connected
[NexusStreamer]Error
[NexusStreamer]Connection Closed

**Comment by ngrimes08** [comment]
so i got past my above issue fixed  by making a change in my config to match what is listed here out on the main page, guess i had a unnecessary true/false statement in the config, but i still don't get a live feed, but still get snapshots okay on my doorbell cam for nest, using the token as the previous updates required. i don't know i'm at a lost on what to do, running this on windows 10. in other news i got my roomba added as an accessory tonight. i would also like to get my samsung washer and dryer added someday as well. i wish homekit would let you blink lights when something happens like a door bell ring. i can get my lights to bling with my washer if i use IFTTT, but no support for the dryer

i do appreciate everyone's hard work to make this all possible, wish i knew more about how to code and program, thank you all very much for your help and creation of this homebridge stuff.

**Comment by jcross74** [comment]
Is the access token still accessible? When following the instructions in the readme, I get a 400 Bad Request response
